[package]
name = "gas_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
toml = "0.7.3"
serde = "1.0.157"
serde_derive = "1.0.157"
unicode-case-mapping = "0.5.0"
